spi/eswin: call spi_read_write_cfg() with correct arguments
spi_read_write_cfg() requires argurment addr to be an integer.
Avoid errors like

    ../drivers/spi/es_spi.c:813:37: error: passing argument 3 of
    ‘spi_read_write_cfg’ makes integer from pointer without a cast
    [-Wint-conversion]
      813 |         spi_read_write_cfg(priv, 3, addr);
          |                                     ^~~~
          |                                     |
          |                                     void *
    ../drivers/spi/es_spi.c:488:72: note: expected ‘u32’
    {aka ‘unsigned int’} but argument is of type ‘void *’

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>